---
- name: config bitwarden service
  hosts: all
  become: yes

  tasks:
    - name: load variables
      include_vars:
        file: secrets.yml
    
    - name: create group bitwarden
      group:
        name: bitwarden
        state: present
        gid: 1030

    - name: create user bitwarden
      user:
         name: bitwarden
         group: bitwarden
         shell: /bin/false
         home: /mnt/docker-data/bitwarden
         uid: 1030

    - name: create /var/lib/bitwarden/certs
      file:
        path: /mnt/docker-data/bitwarden/data
        state: directory
        owner: bitwarden
        group: bitwarden

    - name: create /etc/bitwarden/certs
      file:
        path: /mnt/docker-data/bitwarden/certs
        state: directory
        owner: bitwarden
        group: bitwarden

    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-openssl
        - python-openssl

    - name: generate CA key pair
      openssl_privatekey:
        path: /mnt/docker-data/bitwarden/certs/private-ca.key
        passphrase: "{{ private_key_password }}"
        cipher: aes256
        size: 4096
    
    - name: create ca certificate request
      openssl_csr:
        path: /mnt/docker-data/bitwarden/certs/ca-request.csr
        privatekey_path: /mnt/docker-data/bitwarden/certs/private-ca.key
        privatekey_passphrase: "{{ private_key_password }}"
        country_name: BR
        organization_name: falco.net
        email_address: peregrinus@falco.net
        common_name: falco.net
        digest: sha512
    
    - name: generate a selfsigned certificate (root CA)
      openssl_certificate:
        path: /mnt/docker-data/bitwarden/certs/selfsigned-ca-cert.crt
        privatekey_path: /mnt/docker-data/bitwarden/certs/private-ca.key
        csr_path: /mnt/docker-data/bitwarden/certs/ca-request.csr
        privatekey_passphrase: "{{ private_key_password }}"
        provider: selfsigned
    
    - name: generate bitwarden private key
      openssl_privatekey:
        path: /mnt/docker-data/bitwarden/certs/bitwarden.key
        passphrase: "{{ private_key_password }}"
        cipher: aes256
        size: 4096
    
    - name: create ca certificate request for bitwarden
      openssl_csr:
        path: /mnt/docker-data/bitwarden/certs/bitwarden.csr
        privatekey_path: /mnt/docker-data/bitwarden/certs/bitwarden.key
        privatekey_passphrase: "{{ private_key_password }}"
        country_name: BR
        organization_name: falco.net
        email_address: peregrinus@falco.net
        common_name: falco.net
        digest: sha512

    - name: generate bitwarden certificate signed by root CA 
      openssl_certificate:
        path: /mnt/docker-data/bitwarden/certs/bitwarden.crt
        csr_path: /mnt/docker-data/bitwarden/certs/bitwarden.csr
        ownca_path: /mnt/docker-data/bitwarden/certs/selfsigned-ca-cert.crt
        ownca_privatekey_path: /mnt/docker-data/bitwarden/certs/private-ca.key
        ownca_privatekey_passphrase: "{{ private_key_password }}"
        provider: ownca
