---
- name: config conda
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    user: peregrinus

  tasks:
    - name: create group jupyterhub
      group:
        name: jupyterhub
        state: present
        gid: 3000

    - name: create user jupyterhub
      user:
        name: jupyterhub
        group: jupyterhub
        shell: /bin/false
        home: /var/lib/jupyterhub
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        uid: 3000

    - name: create empty file authorized_keys for jupyterhub
      file:
        path: "/var/lib/jupyterhub/.ssh/authorized_keys"
        owner: jupyterhub
        group: jupyterhub
        state: touch
      become: yes
      become_user: jupyterhub

        #    - name: define variable pubkey for jupyterhub
        #      command: cat /var/lib/jupyterhub/.ssh/id_rsa.pub
        #      register: id_rsa
        #      when: ansible_hostname == "ubuntu-server-02"
        #      notify: define pubkey
        #      become: yes
        #      become_user: jupyterhub
        #
        #    - name: add pubkey for jupyterhub
        #      lineinfile:
        #        path: "/var/lib/jupyterhub/anaconda/.ssh/authorized_keys"
        #        line: "{{ hostvars['ubuntu-server-02']['id_rsa']['stdout'] }}"
        #        #      when: ansible_hostname != "ubuntu-server-02"
        #      become: yes
        #      become_user: jupyterhub

    - name: add user peregrinus to jupyterhub
      user:
         name: "{{ user }}"
         groups: jupyterhub
         append: yes

    - name: download miniconda3
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/anaconda3.sh
        mode: "u=rwx,g=rwx,o=rx"
      become: yes
      become_user: jupyterhub

    - name: install anaconda
      command: "/tmp/anaconda3.sh -b -p /var/lib/jupyterhub/anaconda -u -s -f"
      args:
        creates: /var/lib/jupyterhub/anaconda
      become: yes
      become_user: jupyterhub

    - name: change permissions to jupyterhub directory
      file:
        path: /var/lib/jupyterhub
        state: directory
        owner: jupyterhub
        group: jupyterhub
        recurse: yes

    - name: update conda
      command: /var/lib/jupyterhub/anaconda/bin/conda update --all -y
      become: yes
      become_user: jupyterhub

    - name: install nodejs, notebook, jupyterlab
      command: /var/lib/jupyterhub/anaconda/bin/conda install -y \
        nodejs \
        notebook \
        ipython \
        jupyter \
        jupyterlab \
        flake8
      args:
        chdir: '/var/lib/jupyterhub'
      become: yes
      become_user: jupyterhub

    - name: install jupyterhub, sudospawner, widgetnbextension, ipympl
      command: /var/lib/jupyterhub/anaconda/bin/conda install -y -c conda-forge \
        jupyterhub \
        sudospawner \
        widgetsnbextension \
        ipympl
      args:
        chdir: '/var/lib/jupyterhub'
      become: yes
      become_user: jupyterhub

    - name: "install jupytelab extension: @jupyter/hub-extension"
      command: /var/lib/jupyterhub/anaconda/bin/jupyter labextension install "{{ item }}"
      become: yes
      become_user: jupyterhub
      with_items:
        - "@jupyterlab/hub-extension"
        - "@jupyter-widgets/jupyterlab-manager"
        - "jupyter-matplotlib"
        - "jupyterlab-spreadsheet"
        - "@ijmbarr/jupyterlab_spellchecker"
        - "jupyterlab_tensorboard"
        - "@jupyterlab/plotly-extension"
        - "@jupyterlab/toc"
      args:
        chdir: '/var/lib/jupyterhub'

    - name: update conda to remove problems with versions
      command: /var/lib/jupyterhub/anaconda/bin/conda update --all -y
      become: yes
      become_user: jupyterhub
      args:
        chdir: '/var/lib/jupyterhub'

    - name: update sudoers
      lineinfile:
        path: /etc/sudoers
        line: 'jupyterhub ALL=(%jupyterhub) NOPASSWD: /var/lib/jupyterhub/anaconda/bin/sudospawner'

    - name: create group shadow
      group:
        name: shadow
        state: present

    - name: add user jupyterhub to group shadow and users
      user:
         name: jupyterhub
         groups: shadow,users
         append: yes

    - name: change shadow file
      file:
        path: /etc/shadow
        group: shadow
        mode: "u=rw,g=r"

    - name: generate cert to jupyterhub
      command: openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /var/lib/jupyterhub/jupyterhub.key -out /var/lib/jupyterhub/jupyterhub.crt  -subj "/C=BR/ST=.../L=.../O=.../OU=.../CN=.../emailAddress=retiarus@gmail.com"

    - name: copy config file
      copy:
        src: ./files/jupyterhub_config.py
        dest: /var/lib/jupyterhub/jupyterhub_config.py
        owner: jupyterhub
        group: jupyterhub

    - name: copy sudospawner-singleuser
      copy:
        src: ./files/sudospawner-singleuser
        dest: /var/lib/jupyterhub/anaconda/bin/sudospawner-singleuser
        owner: jupyterhub
        group: jupyterhub
        mode: "g=rx,o=rx"

    - name: copy jupyterhub.service
      copy:
        src: ./files/jupyterhub.service
        dest: /etc/systemd/system/jupyterhub.service
        owner: root
        group: root

    - name: change user to /var/lib/jupyterhub/anaconda
      file:
        path: "/var/lib/jupyterhub/anaconda"
        owner: jupyterhub
        group: jupyterhub
        state: directory
        mode: "u=rwx,g=rwx"
        recurse: yes

    - name: create log file
      file:
        path: /var/log/jupyterhub.log
        owner: jupyterhub
        group: jupyterhub
        state: touch

    - name: copy env file
      copy:
        src: ./files/dscience_env.yml
        dest: /var/lib/jupyterhub/dscience_env.yml
        owner: jupyterhub
        group: jupyterhub

    - name: create env dscience
      command: /var/lib/jupyterhub/anaconda/bin/conda env create -f /var/lib/jupyterhub/dscience_env.yml
      args:
        chdir: '/var/lib/jupyterhub'
      become: yes
      become_user: jupyterhub
