---
- name: create symlinks
  hosts: localhost
  become: yes
  vars:
    server_files:
      - etc/dnsmasq.conf
      - etc/exports
      - etc/lighttpd
      - etc/openvpn
      - etc/default/secure-tunnel@inpe-matrix-openvpn
      - etc/default/secure-tunnel@inpe-matrix-ssh
      - etc/systemd/system/deluged.service
      - etc/systemd/system/deluge-web.service
      - etc/systemd/system/flexget.service
      - etc/systemd/system/secure-tunnel@.service
      - git
      - nfs
      - tftpboot
      - var/lib/deluge
      - var/lib/flexget
      - var/log/deluge
      - var/log/flexget
      - var/log/flexget.log
      - var/www/htdocs
      - windows

  tasks:
    - name: create symlinks
      file: src=/server/{{ item }}
        path=/{{ item }}
        state=link
        force=yes
      with_items: '{{server_files}}'
      ignore_errors: yes

    - name: config permissions to Arquivos-midias
      file: 
         path: "/server/Arquivos-midias"
         owner: peregrinus
         group: users
         state: directory
         recurse: yes

    - name: create user deluge
      user:
         name: deluge
         group: deluge
         shell: /bin/false
         home: /var/lib/deluge

    - name: create user flexget
      user:
         name: flexget
         group: flexget
         shell: /bin/false
         home: /var/lib/flexget

    - name: add user peregrinus to group deluge
      user:
         name: peregrinus
         groups: deluge
         append: yes

    - name: add user flexget to group deluge
      user:
         name: flexget
         groups: deluge
         append: yes

    - name: add user deluge to group flexget
      user:
         name: deluge
         groups: flexget
         append: yes
