---
- name: create symlinks
  hosts: all
  become: yes

  tasks:
  - name: install dnsmasq and lighttpd
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - dnsmasq
      - lighttpd

  - name: copy dnsmasq.conf
    copy:
      src: ./files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root

  - name: create log file for dnsmasq.conf
    file:
      path: /var/log/dnsmasq.log
      owner: root
      group: root
      state: touch

  - name: copy lighttpd.conff
    copy:
      src: ./files/lighttpd.conf
      dest: /etc/lighttpd/lighttpd.conf
      owner: root
      group: root

  - name: copy exports
    copy:
      src: ./files/exports
      dest: /etc/exports
      owner: root
      group: root

  - name: create directories
    file:
      path: "{{ item }}"
      owner: root
      group: root
      state: directory
    loop:
      - /nfs
      - /nfs/gentoo
      - /nfs/ubuntu
      - /nfs/partimag
      - /mnt/windows
      - /var/www/htdocs
      - /var/www/htdocs/clonezilla
      - /var/www/htdocs/clonezilla-amd64
      - /var/www/htdocs/gparted
      - /var/www/htdocs/gparted-amd64

  - name: create directories to tftpboot
    file:
      path: "/tftpboot/{{ item.path }}"
      state: directory
      mode: '{{ item.mode }}'
      owner: root
      group: root
    with_filetree:
    - "./files/tftpboot/"
    when: item.state == 'directory'
    loop_control:
      label: "{{ item.path }}"

  - name: Copy files
    copy:
      src: "{{ item.src }}"
      dest: "/tftpboot/{{ item.path }}"
      mode: "{{ item.mode }}"
      owner: root
      group: root
    with_filetree:
      - "./files/tftpboot/"
    when: item.state == 'file'
    loop_control:
      label: "{{ item.path }}"

  - name: enable service dnsmasq
    systemd:
      name: dnsmasq
      state: started
      enabled: yes

  - name: start service lighttpd
    systemd:
      name: lighttpd
      state: started
      enabled: yes
