---
- name: Install docker
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution.lower() }}/gpg
        state: present

    - name: add docker repository
      apt_repository:
        repo: "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution.lower() }} {{ ansible_distribution_release }}  stable" 
        state: present

    - name: update repositorys
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: install docker-ce
      apt:
        name: docker-ce
        state: present

    - name: start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes

