---
- name: config and initialize filebeat service
  hosts: pve.falco.net
  roles:
    - ansible-modules-bitwarden
    - geerlingguy.java
    - geerlingguy.filebeat
  become: yes
  vars:
    filebeat_version: 7.x
    filebeat_create_config: true
    filebeat_inputs:
      - type: log
        paths:
          - "/var/log/*.log"
    filebeat_output_elasticsearch_enabled: false
    filebeat_output_logstash_enabled: true
    filebeat_output_logstash_hosts:
      - "localhost:5000"
    filebeat_enable_logging: false
    filebeat_log_level: warning
    filebeat_log_dir: /var/log/filebeat
    filebeat_log_filename: filebeat.log

  tasks:
    - name: Set the java_packages variable (Debian/Ubuntu).
      set_fact:
        java_packages:
          - openjdk-8-jdk
      when: ansible_os_family == 'Debian'
