---
- name: config and install gnuradio
  hosts: all
  roles:
    - ansible-modules-bitwarden
  become: yes
  vars:
    user: peregrinus

  tasks:
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libgpm-dev
        - gpm
        - git
        - cmake
        - g++
        - libboost-all-dev
        - libgmp-dev
        - swig
        - python3-numpy
        - python3-mako
        - python3-sphinx
        - python3-lxml
        - doxygen
        - libfftw3-dev
        - libsdl1.2-dev
        - libgsl-dev
        - libqwt-qt5-dev
        - libqt5opengl5-dev
        - python3-pyqt5
        - liblog4cpp5-dev
        - libzmq3-dev
        - python3-yaml
        - python3-click
        - python3-click-plugins
        - python3-zmq
        - python3-scipy

    - name: clone https://github.com/gnuradio/gnuradio.git
      git:
        repo: 'https://github.com/gnuradio/gnuradio.git'
        dest: '/home/{{ user }}/experimentos/gnuradio'
        clone: yes
        update: yes
        recursive: yes
        force: yes
        version: maint-3.8
      become_user: "{{ user }}"

    - name: create dir build
      file:
        path: '/home/{{ user }}/experimentos/gnuradio'
        state: directory
      become_user: "{{ user }}"

    - name: run cmake
      command: "cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3 ../"
      args:
        chdir: "/home/{{ user }}/experimentos/gnuradio/build/"
      become: yes
      become_user: "{{ user }}"

    - name: run make
      command: "make -j4"
      args:
        chdir: "/home/{{ user }}/experimentos/gnuradio/build/"
      become: yes
      become_user: "{{ user }}"

    - name: run make install
      command: "make install"
      args:
        chdir: "/home/{{ user }}/experimentos/gnuradio/build/"
