
---
- name: config and initialize heimdall service
  hosts: all
  become: yes

  tasks:
    - name: create group heimdall
      group:
        name: heimdall
        state: present
        gid: 2002

    - name: create user heimdall
      user:
         name: heimdall
         group: heimdall
         shell: /bin/false
         home: /var/lib/heimdall/
         uid: 2002



         #    - name: generate heimdall service using docker-compose
         #      docker_compose:
         #        project_src: ./docker-files/
         #        services: heimdall
         #        state: present
