---
- name: config and initialize heimdall service
  hosts: all
  roles:
    - ansible-modules-bitwarden
  become: yes

  tasks:
    - name: create group heimdall
      group:
        name: heimdall
        state: present
        gid: 2002

    - name: create user heimdall
      user:
         name: heimdall
         group: heimdall
         shell: /bin/false
         home: /mnt/docker-data/heimdall
         uid: 2002
