---
- name: Install basic aplications
  hosts: "{{ vhost | default('localhost') }}"
  become: yes
  become_user: root
  vars:
    basic_p:
      - syslog-ng
      - openntpd
      - autofs
      - sshfs
    terminal_p:
      - openssh-server
      - openssh-client
      - vim-gtk3
      - zsh
      - tmux
      - ansible
      - git
      - exuberant-ctags
      - wget
      - curl
      - python3-pip
      - python3-dev
      - python3-cffi
      - python-pip
      - python-dev
      - python-cffi
      - libffi-dev
      - virtualenv
      - openssl
      - cifs-utils
      - smbclient
      - nftables
      - acl
      - unrar
      - nbd-client
      - nfstrace
      - build-essential
    pulseaudio_p:
      - pulseaudio-module-zeroconf
      - pulsemixer
      - pamix
    serial_p:
      - screen
      - minicom
    avahi_p:
      - avahi-daemon
      - avahi-discover
      - avahi-utils
      - libnss-mdns
      - mdns-scan
    docker_p:
      - docker
      - docker.io
      - python3-docker
      - python-docker
    container_lxc_p:
      - lxc
      - lxc-dev
      - lxd
    bridges_p:
      - ifenslave
      - bridge-utils
    server_p:
      - samba
      - nfs4-acl-tools
      - nfs-kernel-server
      - nfs-common
      - nbd-server
    desktop_p:
      - awesome
      - sakura
      - uget
      - mate-desktop-environment
      - pluma
      - synergy
      - spice-client-gtk
      - remmina-plugin-spice
      - remmina-plugin-exec
      - remmina-plugin-telepathy
      - remmina-plugin-xdmcp
      - remmina-plugin-nx
      - virt-manager
      - pavucontrol
      - smplayer
      - mpv
      - mplayer
      - mplayer-gui
      - vlc
      - gimp
      - inkscape
      - chromium-browser
      - deluge
      - software-properties-common
      - apt-transport-https
      - wget
    nodejs_p:
      - npm
      - nodejs
    virt_p:
      - openvswitch-switch
      - openvswitch-common
      - libvirt-daemon
      - libvirt-bin
      - libvirglrenderer-dev
      - libvirglrenderer0
    latex_p:
      - texlive-latex-base
      - texlive-latex-base-doc
      - texlive-latex-recommended
      - texlive-latex-recommended-doc
      - texlive-latex-extra
      - texlive-latex-extra-doc
      - texlive-bibtex-extra
      - texlive-extra-utils
      - texlive-pictures
      - texlive-publishers
      - texlive-science
      - texlive-humanities
      - texlive-games
      - texlive-xetex
      - texlive-full
      - texlive-luatex
      - texlive-lang-portuguese
    target: terminal
    user: peregrinus
    nfs_server: ubuntu-server-02

  tasks:
    - include_tasks: basic.yml
      when: target == "basic"

    - include_tasks: terminal.yml
      when: target == "terminal"

    - include_tasks: avahi.yml
      when: target == "avahi"

    - include_tasks: server.yml
      when: target == "server"

    - include_tasks: desktop.yml
      when: target == "desktop"

    - include_tasks: nodejs.yml
      when: target == "nodejs"

    - include_tasks: virt.yml
      when: target == "virt"

    - include_tasks: nfs-client.yml
      when: target == "nfs-client"

    - include_tasks: nfs-server.yml
      when: target == "nfs-server" and ansible_hostname == nfs_server

    - include_tasks: full.yml
      when: target == "full"

    - name: install task
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ set }}"
      when: set is defined
      ignore_errors: True
...
