---
all:
  children:

    spark:
      hosts:
        ubuntu-01:
        ubuntu-02:
          ansible_connection: local
        ubuntu-03:
        falco03:
        falco04:
        falco06:
      vars:
        ansible_become: true
        ansible_become_method: sudo

    ansible_course:
      hosts:
        ubuntu-c:
        ubuntu1:
        ubuntu2:
        ubuntu3:
        centos1:
        centos2:
        centos3:

    workhome:
      hosts:
        ubuntu-01:
        ubuntu-02:
        ubuntu-03:
        falco03:
        falco04:
        falco05:
        falco06:

    synergy:
      hosts:
        falco03:
        falco06:
