---
all:
  children:

    spark:
      hosts:
        ubuntu-server-01:
        ubuntu-server-02:
          ansible_connection: local
        ubuntu-server-03:
        falco03:
        falco04:
        falco06:
      vars:
        ansible_become: true
        ansible_become_method: sudo

    ansible_course:
      hosts:
        ubuntu-c:
        ubuntu1:
        ubuntu2:
        ubuntu3:
        centos1:
        centos2:
        centos3:

  hosts:
    kali:
