---
- name: Install basic aplications
  hosts: "{{ vhost | default('localhost') }}"
  become: yes
  become_user: root
  vars:
    basic_p:
      - syslog-ng
      - openntpd
      - autofs
      - sshfs
    terminal_p:
      - openssh-server
      - openssh-client
      - vim-gtk3
      - zsh
      - tmux
      - ansible
      - git
      - exuberant-ctags
      - wget
      - curl
      - python3-pip
      - python-pip
      - virtualenv
      - openssl
      - pulseaudio-module-zeroconf
      - pulsemixer
      - pamix
      - cifs-utils
      - smbclient
      - nftables
      - acl
    avahi_p:
      - avahi-daemon
      - avahi-discover
      - avahi-utils
      - libnss-mdns
      - mdns-scan
    server_p:
      - docker
      - docker.io
      - lxc
      - lxc-dev
      - lxd
      - ifenslave
      - bridge-utils
      - samba
    desktop_p:
      - awesome
      - sakura
      - uget
      - mate-desktop-environment
      - pluma
      - synergy
      - spice-client-gtk
      - remmina-plugin-spice
      - remmina-plugin-exec
      - remmina-plugin-telepathy
      - remmina-plugin-xdmcp
      - remmina-plugin-nx
      - virt-manager
      - pavucontrol
      - smplayer
      - mpv
      - mplayer
      - mplayer-gui
      - vlc
      - gimp
      - inkscape
      - chromium-browser
      - deluge
    nodejs_p:
      - npm
      - nodejs
    virt_p:
      - openvswitch-switch
      - openvswitch-common
      - libvirt-daemon
      - libvirt-bin
      - libvirglrenderer-dev
      - libvirglrenderer0
    target: "terminal"

  tasks:
    - include_tasks: basic.yml
      when: target == "basic"

    - include_tasks: terminal.yml
      when: target == "terminal"

    - include_tasks: avahi.yml
      when: target == "avahi"

    - include_tasks: server.yml
      when: target == "server"

    - include_tasks: desktop.yml
      when: target == "desktop"

    - include_tasks: nodejs.yml
      when: target == "nodejs"

    - include_tasks: virt.yml
      when: target == "virt"

    - include_tasks: full.yml
      when: target == "full"
...
